---
  apiVersion: v1
  kind: Service
  metadata:
    name: service-cluster-ip
  spec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      targetPort: 1337
    selector:
      name: grpc-and-kubernetes